# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f174c5aa1aea6f9a216a9d9f3eb0698c380139fe0ab096a7dbc9829288fb7320ae5439d0f898dcf9f62c0fa495eeeb47951dbe529424d32b7f2da3970b0f1d48

test:
  secret_key_base: d55daafe78fe9e9af6b374e2db83bbebc9120e9eeed1e79a267c56d40e7cf4a8598b32ea5966ccbd5162acd49050730ce72a388538a36d06889e056b5bd1288e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
